#!/bin/bash
# Project Launcher

SHELL_PATH=$(cd "$(dirname "`readlink $0`")";pwd)

PROJECT_NAME=$2
if [ ! -n "$2" ]; then 
    PROJECT_NAME="$(basename "`pwd`")"
fi
if [ "$2" == "-g" ]; then 
    PROJECT_NAME=`cat $(pwd)/../.cntrLst`
fi

cd `pwd` && cd ..

if [ `whoami` = "root" ];then
	echo "您不应当使用 Root 身份来运行脚本。"
    echo " - 当部分命令需要 Root 身份时，脚本会自动 并要求您赋权"
    exit
fi

if [ "$1" == "test" ]; then 
    echo `pwd`
    echo $SHELL_PATH
    echo $PROJECT_NAME
    exit
fi

if [ "$1" == "install" ]; then 
    rm -f /usr/bin/pls
    ln -s ${SHELL_PATH}/pls /usr/bin/pls
    exit
fi

if [ "$1" == "path" ]; then 
    echo "pls file: ${SHELL_PATH}/pls"
    exit
fi

if [ ! -n "$1" ]; then 
    docker-compose.exe exec ${PROJECT_NAME} /bin/zsh
    exit
fi

if [ "$1" == "zsh" ]; then 
    docker-compose.exe exec ${PROJECT_NAME} /bin/zsh
    exit
fi

if [ "$1" == "bash" ]; then 
    docker-compose.exe exec ${PROJECT_NAME} /bin/bash
    exit
fi

if [ "$1" == "sh" ]; then 
    docker-compose.exe exec ${PROJECT_NAME} /bin/sh
    exit
fi

if [ "$1" == "up" ]; then 
    docker-compose.exe up --detach --build ${PROJECT_NAME}
    exit
fi

if [ "$1" == "debug" ]; then 
    docker-compose.exe up --build --force-recreate ${PROJECT_NAME}
    exit
fi

if [ "$1" == "stop" ]; then 
    docker-compose.exe stop --timeout 12 ${PROJECT_NAME}
    exit
fi

if [ "$1" == "restart" ]; then 
    docker-compose.exe restart --timeout 12 ${PROJECT_NAME}
    exit
fi

if [ "$1" == "init" ]; then 
    docker-compose.exe up --detach --build --force-recreate ${PROJECT_NAME}
    exit
fi

if [ "$1" == "clear" ]; then 
    docker.exe stop $(docker ps -a -q)
    docker.exe container prune --force
    exit
fi

if [ "$1" == "cleari" ]; then 
    docker.exe image prune --force --all
    exit
fi

if [ "$1" == "--help" ]; then 
    cat ${SHELL_PATH}/readme.md
    exit
fi

echo "此指令不存在，请输入 pls --help 获取帮助信息。"
